//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface LoginResponse {
    message: string;
    username: string;
}

export interface AuthCheckResponse {
    isAuthenticated: boolean;
    username?: string;
}

export class Client {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        const baseUrl = import.meta.env.VITE_BASE_URL || 'https://dayz-promo.ru';
        this.baseUrl = `${baseUrl}/api`;
        this.http = http || window as any;
    }

    // Фабричный метод для создания клиента
    static create(): Client {
        return new Client();
    }

    protected transformOptions = (options: RequestInit): Promise<RequestInit> => {
        return Promise.resolve({
            ...options,
            credentials: 'include',
            headers: {
                ...options.headers,
                'Content-Type': 'application/json',
                'Accept': 'application/json',
            }
        });
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    register(body: RegisterModel | undefined): Promise<void> {
        let url_ = this.baseUrl + "/Auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processRegister(_response);
        });
    }

    protected processRegister(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body: LoginModel | undefined): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/Auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            credentials: 'include'
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: Response): Promise<LoginResponse> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }

        if (status === 405) {
            throw new Error('Method not allowed. Please check if the server accepts POST requests.');
        }
        
        if (status === 200) {
            return response.json().then(data => {
                if (!data || typeof data.message !== 'string' || typeof data.username !== 'string') {
                    throw new Error('Invalid response format');
                }
                return {
                    message: data.message,
                    username: data.username
                };
            });
        }
        
        return response.text().then(text => {
            try {
                const data = JSON.parse(text);
                throw new Error(data.message || `Server error: ${status}`);
            } catch {
                throw new Error(`Server error: ${text || status}`);
            }
        });
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    generatePromoPOST(body: PostImageDto): Promise<PromoCode> {
        let url_ = this.baseUrl + "/GeneratePromo";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGeneratePromoPOST(_response);
        });
    }

    protected processGeneratePromoPOST(response: Response): Promise<PromoCode> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }

        if (status === 403) {
            throw new Error('Access Denied');
        }

        if (status === 400) {
            return response.text().then(text => {
                throw new Error(text || 'Invalid request data');
            });
        }
        
        if (status === 201) {
            return response.json().then(data => {
                if (!data || !data.id) {
                    throw new Error('Invalid response format');
                }
                return data as PromoCode;
            });
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }

    /**
     * @return OK
     */
    generatePromoGET(id: string): Promise<void> {
        let url_ = this.baseUrl + "/GeneratePromo/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGeneratePromoGET(_response);
        });
    }

    protected processGeneratePromoGET(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    logout(): Promise<void> {
        let url_ = this.baseUrl + "/Auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {}
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return Promise.resolve();
        });
    }

    checkAuth(): Promise<AuthCheckResponse> {
        let url_ = this.baseUrl + "/Auth/check";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {}
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processCheckAuth(_response);
        });
    }

    protected processCheckAuth(response: Response): Promise<AuthCheckResponse> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            return Promise.resolve({ isAuthenticated: false });
        }
        
        if (status === 200) {
            return response.json().then(data => {
                if (typeof data.isAuthenticated !== 'boolean') {
                    throw new Error('Invalid response format');
                }
                return {
                    isAuthenticated: data.isAuthenticated,
                    username: data.username
                };
            });
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }

    /**
     * @return OK
     */
    getPromocodesList(): Promise<PromoCode[]> {
        let url_ = this.baseUrl + "/GeneratePromo/GetPromocodesList";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json",
                "Content-Type": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetPromocodesList(_response);
        });
    }

    protected processGetPromocodesList(response: Response): Promise<PromoCode[]> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }

        if (status === 403) {
            throw new Error('Access Denied');
        }
        
        if (status === 200) {
            return response.json().then(data => {
                if (!Array.isArray(data)) {
                    throw new Error('Invalid response format');
                }
                return data.map(item => ({
                    ...item,
                    expirationDate: item.expirationDate
                }));
            });
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }

    /**
     * @return OK
     */
    getPromo(id: string): Promise<PromoResponse> {
        let url_ = this.baseUrl + "/GeneratePromo/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetPromo(_response);
        });
    }

    protected processGetPromo(response: Response): Promise<PromoResponse> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }
        
        if (status === 200) {
            return response.json().then(data => {
                if (!data || typeof data.promo !== 'string' || 
                    typeof data.qrCodeUrl !== 'string' || 
                    typeof data.finalImageUrl !== 'string' ||
                    typeof data.expirationDate !== 'string') {
                    throw new Error('Invalid response format');
                }
                return {
                    ...data,
                    qrCodeUrl: `/api/${data.qrCodeUrl}`,
                    finalImageUrl: `/api/${data.finalImageUrl}`
                };
            });
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }

    updatePromo(id: string, body: PostImageDto): Promise<PromoCode> {
        let url_ = this.baseUrl + `/GeneratePromo/${id}`;
        url_ = url_.replace(/[?&]$/, "");

        // Преобразуем дату в ISO строку, если она передана как объект Date
        const formattedBody = {
            ...body,
            expirationDate: typeof body.expirationDate === 'string' 
                ? body.expirationDate 
                : new Date(body.expirationDate).toISOString()
        };

        const content_ = JSON.stringify(formattedBody);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processUpdatePromo(_response);
        });
    }

    deletePromo(id: string): Promise<void> {
        let url_ = this.baseUrl + `/GeneratePromo/${id}`;
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE"
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processDeletePromo(_response);
        });
    }

    protected processUpdatePromo(response: Response): Promise<PromoCode> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }

        if (status === 403) {
            throw new Error('Access Denied');
        }

        if (status === 404) {
            throw new Error('Promo not found');
        }

        if (status === 400) {
            return response.text().then(text => {
                throw new Error(text || 'Invalid request data');
            });
        }
        
        if (status === 200) {
            return response.json().then(data => {
                if (!data || !data.id) {
                    throw new Error('Invalid response format');
                }
                return data as PromoCode;
            });
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }

    protected processDeletePromo(response: Response): Promise<void> {
        if (!response || !response.status) {
            throw new Error('Invalid response received');
        }

        const status = response.status;
        
        if (status === 401) {
            throw new Error('Unauthorized');
        }

        if (status === 403) {
            throw new Error('Access Denied');
        }

        if (status === 404) {
            throw new Error('Promo not found');
        }
        
        if (status === 204) {
            return Promise.resolve();
        }
        
        throw new Error(`Unexpected status code: ${status}`);
    }
}

export interface LoginModel {
    username?: string | undefined;
    password?: string | undefined;
}

export interface PostImageDto {
    name: string;
    expirationDate: string;
}

export interface RegisterModel {
    username?: string | undefined;
    password?: string | undefined;
}

export interface PromoCode {
    id: string;
    name: string;
    promo: string;
    expirationDate: string;
    qrCodePath?: string;
    finalImagePath?: string;
}

export interface PromoResponse {
    promo: string;
    qrCodeUrl: string;
    finalImageUrl: string;
    expirationDate: string;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}